services:
  prod:
    build:
      context: .
      target: prod
    image: cadvisor_prod:latest

  dev:
    build:
      context: .
      target: dev
    image: cadvisor_dev:latest


  test:
    build:
      context: .
      target: test
    image: cadvisor_test:latest