services:
  prod:
    build:
      context: .
      target: prod
      args:
        DIAGNOSTICS_ANALYZERS: "${DIAGNOSTICS_ANALYZERS}"
    image: cadvisor_prod:latest

  dev:
    build:
      context: .
      target: dev
    image: cadvisor_dev:latest

