services:
  prod:
    build:
      context: .
      target: prod
      args:
        CADVISOR_MONITOR_DIAGNOSTICS: "${CADVISOR_MONITOR_DIAGNOSTICS}"
        CADVISOR_MONITOR_PARAMS: "${CADVISOR_MONITOR_PARAMS}"
    image: cadvisor_prod:latest

  dev:
    build:
      context: .
      target: dev
    image: cadvisor_dev:latest

